freq_table.hi:
freq_table.hi0:
	.db $1a
	.db $19
	.db $17
	.db $16
	.db $15
	.db $14
	.db $12
	.db $11
	.db $10
	.db $0f
	.db $0f
	.db $0e
    .db $00, $00, $00, $00              ; filler
freq_table.hi1:
	.db $0d
	.db $0c
	.db $0b
	.db $0b
	.db $0a
	.db $0a
	.db $09
	.db $08
	.db $08
	.db $07
	.db $07
	.db $07
    .db $00, $00, $00, $00              ; filler
freq_table.hi2:
	.db $06
	.db $06
	.db $05
	.db $05
	.db $05
	.db $05
	.db $04
	.db $04
	.db $04
	.db $03
	.db $03
	.db $03
    .db $00, $00, $00, $00              ; filler
freq_table.hi3:
	.db $03
	.db $03
	.db $02
	.db $02
	.db $02
	.db $02
	.db $02
	.db $02
	.db $02
	.db $01
	.db $01
	.db $01
    .db $00, $00, $00, $00              ; filler
freq_table.hi4:
	.db $01
	.db $01
	.db $01
	.db $01
	.db $01
	.db $01
	.db $01
	.db $01
	.db $01
	.db $00
	.db $00
	.db $00
    .db $00, $00, $00, $00              ; filler
freq_table.hi5:
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
    .db $00, $00, $00, $00              ; filler
freq_table.hi6:
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
    .db $00, $00, $00, $00              ; filler
freq_table.hi7:
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
    .db $00, $00, $00, $00              ; filler
freq_table.hi8:
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
	.db $00
    .db $00, $00, $00, $00              ; filler
freq_table.lo:
freq_table.lo0:
	.db $ba
	.db $3a
	.db $cf
	.db $79
	.db $36
	.db $06
	.db $e6
	.db $d6
	.db $d6
	.db $e4
	.db $00
	.db $28
    .db $00, $00, $00, $00              ; filler
freq_table.lo1:
	.db $5d
	.db $9d
	.db $e7
	.db $3c
	.db $9b
	.db $03
	.db $73
	.db $eb
	.db $6b
	.db $f2
	.db $80
	.db $14
    .db $00, $00, $00, $00              ; filler
freq_table.lo2:
	.db $ae
	.db $4e
	.db $f3
	.db $9e
	.db $4d
	.db $01
	.db $b9
	.db $75
	.db $35
	.db $f9
	.db $c0
	.db $8a
    .db $00, $00, $00, $00              ; filler
freq_table.lo3:
	.db $57
	.db $27
	.db $f9
	.db $cf
	.db $a6
	.db $80
	.db $5c
	.db $3a
	.db $1a
	.db $fc
	.db $e0
	.db $c5
    .db $00, $00, $00, $00              ; filler
freq_table.lo4:
	.db $ab
	.db $93
	.db $7c
	.db $67
	.db $53
	.db $40
	.db $2e
	.db $1d
	.db $0d
	.db $fe
	.db $f0
	.db $e2
    .db $00, $00, $00, $00              ; filler
freq_table.lo5:
	.db $d5
	.db $c9
	.db $be
	.db $b3
	.db $a9
	.db $a0
	.db $97
	.db $8e
	.db $86
	.db $7f
	.db $78
	.db $71
    .db $00, $00, $00, $00              ; filler
freq_table.lo6:
	.db $6a
	.db $64
	.db $5f
	.db $59
	.db $54
	.db $50
	.db $4b
	.db $47
	.db $43
	.db $3f
	.db $3c
	.db $38
    .db $00, $00, $00, $00              ; filler
freq_table.lo7:
	.db $35
	.db $32
	.db $2f
	.db $2c
	.db $2a
	.db $28
	.db $25
	.db $23
	.db $21
	.db $1f
	.db $1e
	.db $1c
    .db $00, $00, $00, $00              ; filler
freq_table.lo8:
	.db $1a
	.db $19
	.db $17
	.db $16
	.db $15
	.db $14
	.db $12
	.db $11
	.db $10
	.db $0f
	.db $0f
	.db $0e

noise_table:
	.db $84
	.db $ad
	.db $af
	.db $b2
	.db $b5
	.db $b7
	.db $b9
	.db $bb
	.db $bd
	.db $bf
	.db $81
	.db $83
